== Criação  árvore

=criar 0 0



==Inserir Direita

=insdir 'p' 0



==Inserir Direita

=insdir 'n' 0



==Ir Pai

=irpai 0



==Inserir Esquerda

=insesq 'y' 0



==Inserir Esquerda

=insesq 'k' 0



==Ir Pai

=irpai 0



==Inserir Direita

=insdir 'v' 0



==Inserir Direita

=insdir 'c' 0



==Ir Pai

=irpai 0



==Inserir Esquerda

=insesq 'x' 0



==Inserir Direita

=insdir 'a' 0



==Ir Pai

=irpai 0



==Inserir Esquerda

=insesq 'b' 0

== Costura
=costurar 0